export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const START_FETCHING = "START_FETCHING";
export const SUCCESS_FETCHING = "SUCCESS_FETCHING";
export const FAILUR_FETCHING = "FAILUR_FETCHING";
